server:
  port: 8084
  shutdown: graceful

spring:
  profiles:
    active: ${PROFILE:local}

  lifecycle:
    timeout-per-shutdown-phase: "60s"

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: finda-batch

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    overwrite-existing-jobs: true
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: Finda-Batch-Scheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: ${QUARTZ_CLUSTERED:false}
            useProperties: false
            misfireThreshold: 300000
            acquireTriggersWithinLock: true
            txIsolationLevelSerializable: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-batch/master.xml

grpc:
  client:
    volunteer-service:
      address: static://${VOLUNTEER_GRPC_HOST:localhost}:${VOLUNTEER_GRPC_PORT:9091}
      negotiation-type: plaintext
