syntax = "proto3";

package auth;

option java_package = "finda.findaauth.adapter.in.grpc";
option java_multiple_files = true;

service AuthService {
  rpc GetDeviceToken (UserRequest) returns (DeviceTokenResponse);
  rpc GetDeviceTokens (UserListRequest) returns (DeviceTokenListResponse);
}

message UserRequest {
  string user_id = 1;
}

message UserListRequest {
  repeated string user_ids = 1;
}

message DeviceTokenResponse {
  string device_token = 1;
  string os = 2;
}

message DeviceTokenListResponse {
  repeated DeviceTokenResponse tokens = 1;
}

message UserDevice {
  string user_id = 1;
  repeated DeviceTokenResponse devices = 2;
}

message UserDeviceListResponse {
  repeated UserDevice users = 1;
}
