server:
  port: 8083
  shutdown: graceful # 처리 중인 요청을 중간에 끊지 않고 안전하게 마무리하기 위함
  servlet:
    context-path: /finda-notification

grpcs:
  server:
    port: 9093
  client:
    auth-service:
      address: ${AUTH_GRPC_ADDRESS} # auth는 서버 역할이라 포트만 열면 되고 notification은 gRPC 클라이언트 역할이라 어디로 연결할지 주소를 알아야 하기 때문에 환경변수 분리

spring:
  profiles:
    active: ${PROFILE:local}

  lifecycle:
    timeout-per-shutdown-phase: "60s" # 60초 동안 현재 처리 중인 요청을 기다림

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${NOTIFICATION_MYSQL_HOST}:${NOTIFICATION_DB_PORT}/${NOTIFICATION_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${NOTIFICATION_MYSQL_USERNAME}
    password: ${NOTIFICATION_MYSQL_PASSWORD}

  Kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: finda-notification

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-notification/master.xml

passport:
  secret-key: ${PASSPORT_SECRET_KEY}

firebase:
  service-account-json: ${FIREBASE_SERVICE_ACCOUNT_JSON}
