server:
  port: 8081
  shutdown: graceful
  servlet:
    context-path: /finda-auth

grpc:
  server:
    port: 9090
  client:
    volunteer-service:
      address: static://${VOLUNTEER_GRPC_HOST:localhost}:${VOLUNTEER_GRPC_PORT:9091}
      negotiation-type: plaintext

spring:
  profiles:
    active: ${PROFILE:local}

  lifecycle:
    timeout-per-shutdown-phase: "60s"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: false
        show_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100

    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:xavexxn@gmail.com}
    password: ${MAIL_PASSWORD:ajtp mdgv uycz cnvk}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-auth/master.xml

jwt:
  secret: ${JWT_SECRET:aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789aBcDeFgHiJkLmNoPqRsTuVwXyZ01}
  access-exp: 3600
  refresh-exp: 604800
  header: Authorization
  prefix: "Bearer "

passport:
  secret-key: ${PASSPORT_SECRET_KEY:aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789aBcDeFgHiJkLmNoPqRsTuVwXyZ01}

teacher:
  signup-secret: ${TEACHER_SIGNUP_SECRET:hello}
