object DependencyVersions {
    const val MYSQL = "8.0.28"
    const val UUID_TIME_VERSION = "3.1.4"
    const val JACKSON_VERSION = "2.16.1"
    const val JWT = "0.11.5"
    const val SPRING_CLOUD = "2023.0.3"
    const val NETTY_DNS = "4.1.108.Final"
    const val GRPC_STARTER = "2.15.0.RELEASE"
    const val GRPC = "1.59.0"
    const val PROTOBUF = "3.24.0"
    const val JAVAX_ANNOTATION = "1.3.2"
    const val FIRE_BASE = "9.5.0"
    const val APACHE_POI = "5.3.0"
    const val PDF_BOX = "3.0.1"
    const val SWAGGER_VERSION = "2.6.0"
}
